/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kamra;

import java.util.Optional;

/**
 *
 * @author Hoffmann József
 */
public class AlapanyagFelvitelDialog extends javax.swing.JDialog {

    private boolean ok;
    private Alapanyag alapanyag;
    private Optional<Alapanyag> optAlapanyag;
    
    public boolean isOk() {
        return ok;
    }
    
    public Optional<Alapanyag> getOptAlapanyag() {
        return this.optAlapanyag;
    }
    public Alapanyag getAlapanyag() {
        return this.alapanyag;
}
    /**
     * Creates new form alapanyagFelvitelDialog
     */
    public AlapanyagFelvitelDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    public AlapanyagFelvitelDialog(java.awt.Frame parent, boolean modal, Optional<Alapanyag> optAlapanyag) {

        super(parent, modal);
        initComponents();
        this.optAlapanyag = optAlapanyag;
        
        if (optAlapanyag.isPresent()) {
            tfAlapanyagNev.setText(optAlapanyag.get().getNev());
            tfMennyisegEgyseg.setText(optAlapanyag.get().getMe());
            tfMennyiseg.setText("" + optAlapanyag.get().getMin());
        }
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfAlapanyagNev = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfMennyisegEgyseg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfMennyiseg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btOK = new javax.swing.JButton();
        btMegse = new javax.swing.JButton();
        jComboBoxME = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Új alapanyag hozzáadása / módosítása");

        tfAlapanyagNev.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Alapanyag neve:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mennyiség egysége: ");

        tfMennyisegEgyseg.setEditable(false);
        tfMennyisegEgyseg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Minimális mennyiség:");

        tfMennyiseg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfMennyiseg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfMennyisegFocusLost(evt);
            }
        });
        tfMennyiseg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMennyisegActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("A program figyelmeztet, ha ezen érték alá csökken a készlet mennyisége");

        btOK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btOK.setText("OK");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        btMegse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btMegse.setText("Mégse");
        btMegse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMegseActionPerformed(evt);
            }
        });

        jComboBoxME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Válassz!", "kg", "liter", "darab" }));
        jComboBoxME.setToolTipText("Válassz mennyiség egységet!");
        jComboBoxME.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMEItemStateChanged(evt);
            }
        });
        jComboBoxME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfMennyiseg, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxME, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfMennyisegEgyseg)
                                .addGap(272, 272, 272)))
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfAlapanyagNev, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btOK, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(btMegse, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfAlapanyagNev, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxME, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMennyisegEgyseg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfMennyiseg, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOK, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMegse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        ok = true;          
        boolean kitoltott = false;
        if (tfAlapanyagNev.getText().isEmpty()) {
            tfAlapanyagNev.setText("Nem lehet üres!");
            kitoltott = false;
        } else { 
            kitoltott = true;
        }
        
        
        if (tfMennyisegEgyseg.getText().isEmpty()) {
            tfMennyisegEgyseg.setText("Nem lehet üres!");
            kitoltott = false;
        } else {
            kitoltott = true;
        }    
        try {
            double doubleMennyiseg = Double.parseDouble(tfMennyiseg.getText());
            if (optAlapanyag == null) {
                Alapanyag ujAlapanyag = new Alapanyag(tfAlapanyagNev.getText(), tfMennyisegEgyseg.getText(), doubleMennyiseg);
                optAlapanyag = Optional.of(ujAlapanyag);
            } else {    
                Alapanyag modAlapanyag = new Alapanyag(optAlapanyag.get().getId(), tfAlapanyagNev.getText(), tfMennyisegEgyseg.getText(), doubleMennyiseg);
                optAlapanyag = Optional.of(modAlapanyag);
            }
            kitoltott = true;                      
        } catch (NumberFormatException nfe) {
            tfMennyiseg.setText("Számot kérek!");
            kitoltott = false;
        }    
        if (kitoltott)  {
            
            setVisible(false);
        }
            
    }//GEN-LAST:event_btOKActionPerformed

    private void tfMennyisegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMennyisegActionPerformed


    }//GEN-LAST:event_tfMennyisegActionPerformed

    private void tfMennyisegFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMennyisegFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMennyisegFocusLost

    private void btMegseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMegseActionPerformed
        ok = false; 
        setVisible(false); 
    }//GEN-LAST:event_btMegseActionPerformed

    private void jComboBoxMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMEActionPerformed
        
    }//GEN-LAST:event_jComboBoxMEActionPerformed

    private void jComboBoxMEItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMEItemStateChanged
        if (evt.getStateChange() == 1) {
            
            if ((String) evt.getItem() != "Válassz!")
            tfMennyisegEgyseg.setText((String) evt.getItem());
        }
            
    }//GEN-LAST:event_jComboBoxMEItemStateChanged

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlapanyagFelvitelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlapanyagFelvitelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlapanyagFelvitelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlapanyagFelvitelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlapanyagFelvitelDialog dialog = new AlapanyagFelvitelDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMegse;
    private javax.swing.JButton btOK;
    private javax.swing.JComboBox<String> jComboBoxME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfAlapanyagNev;
    private javax.swing.JTextField tfMennyiseg;
    private javax.swing.JTextField tfMennyisegEgyseg;
    // End of variables declaration//GEN-END:variables
}
